# Generated by Django 5.0.3 on 2024-03-14 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('about_applicant', models.TextField()),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_board.joblisting')),
            ],
        ),
    ]
